version: "3.9"

services:
  db:
    image: postgres:15
    container_name: core_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: coredb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build: ./api
    container_name: core_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:secretpassword@db:5432/coredb
    ports:
      - "8000:8000"
